name: Deploy Frontend to S3

on:
  push:
    branches:
      - deploy-to-s3
env:
  AWS_REGION: us-east-2
  S3_BUCKET: order-service-client

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npx ng build --configuration=production

      - name: Deploy to S3 Bucket
        run: |
          aws s3 sync dist/OrderServiceClient/ s3://${{ env.S3_BUCKET }} \
          --delete \
          --acl public-read
